### ISSUE TITLE
Upload error on YARN cluster

### ISSUE THREAD

**Issue by Jaeki** [ytchen0323/cloud-scale-bwamem#1]
Hi,

I am running Spark on CDH5 cluster. CDH version is 5.4.3 and the cluster is consist of 16 datanodes.
When I tried to upload fasta files as your instruction I got fail along with some WARNING and ERROR like below.
I have tried to change the dataset (fasta files). But it shows same error for the all paired dataset.
Could you guys give some advise to run your CS BWAMEM on a cluster?
or point out the download location some working dataset?

Thanks in advance.

The command that I used...

$ spark-submit --master yarn-client cloud-scale-bwamem-0.1.0-assembly.jar upload-fastq 1 3 /dn5/ERR09157_1.fastq /dn6/ERR09157_2.fastq ./bwamem

15/09/18 11:41:18 INFO BlockManagerMasterActor: Registering block manager nodes-45:54274 with 530.3 MB RAM, BlockManagerId(1, nodes-45, 54274)
[WARNING] Avro: Invalid default for field comment: null not a "bytes"
Error: Input format not handled
Error: Input format not handled
[WARNING] Avro: Invalid default for field comment: null not a "bytes"
15/09/18 11:41:18 INFO deprecation: mapred.output.dir is deprecated. Instead, use mapreduce.output.fileoutputformat.outputdir
15/09/18 11:41:18 INFO FileOutputCommitter: File Output Committer Algorithm version is 1

............................
15/09/18 11:41:22 INFO TaskSetManager: Starting task 2.0 in stage 0.0 (TID 2, nodes-38, PROCESS_LOCAL, 5564540 bytes)
15/09/18 11:41:22 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, nodes-38): java.lang.RuntimeException: Null-value for required field: seq0
        at parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:115)
        at parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:87)
        at parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:44)
        at parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:116)
        at parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:123)
        at parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:42)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:1000)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:979)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

15/09/18 11:41:23 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 3, nodes-45, PROCESS_LOCAL, 5512867 bytes)
15/09/18 11:41:23 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 3257 ms on nodes-45 (1/3)
.........................
15/09/18 11:41:24 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 5, nodes-45, PROCESS_LOCAL, 5512867 bytes)
15/09/18 11:41:24 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 5) on executor nodes-45: java.lang.RuntimeException (Null-value for required field: seq0) [duplic ate 3]
15/09/18 11:41:24 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
15/09/18 11:41:24 INFO YarnScheduler: Removed TaskSet 0.0, whose tasks have all completed, from pool
15/09/18 11:41:24 INFO YarnScheduler: Cancelling stage 0
15/09/18 11:41:24 INFO DAGScheduler: Job 0 failed: saveAsNewAPIHadoopFile at FASTQLocalFileLoader.scala:356, took 5.334327 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in  stage 0.0 (TID 5, nodes-45): java.lang.RuntimeException: Null-value for required field: seq0
        at parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:115)
        at parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:87)
        at parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:44)
        at parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:116)
        at parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:123)
        at parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:42)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:1000)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:979)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1203)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1191)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1191)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
15/09/18 11:41:24 ERROR LiveListenerBus: Listener EventLoggingListener threw an exception
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:144)
        at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:144)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:144)
        at org.apache.spark.scheduler.EventLoggingListener.onStageCompleted(EventLoggingListener.scala:165)
        at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:32)
        at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
        at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
        at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:53)
        at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:36)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:76)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply(AsynchronousListenerBus.scala:61)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply(AsynchronousListenerBus.scala:61)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1617)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:60)
Caused by: java.io.IOException: Filesystem closed
        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:794)
        at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1998)
        at org.apache.hadoop.hdfs.DFSOutputStream.hflush(DFSOutputStream.java:1959)
        at org.apache.hadoop.fs.FSDataOutputStream.hflush(FSDataOutputStream.java:130)
        ... 19 more

**Comment by ytchen0323** [comment]
Hi Jaeki,
This is Yu-Ting. What is the size of your FASTQ file? By default, if you don't set the -bn option, the default value will be 250000. This parameter means the number of lines to be read in one batch. It must be a multiple of 4 since in the fastq format since each read contains four lines. You may need to check if your input FASTQ is large enough.

I will suggest that you may use a larger number such as 1,000,000 or 4,000,000 for one batch. In this case, your file partition in the HDFS will be large enough. You may also want to enlarge the number of partition per batch "3" into a larger number, such as 100. In this case, you will have more file partition so that you can use more thread for computation in the alignment step.

In addition, I suggest that you can also add parameters for Spark. For example, you may specify the whole command to be "SPARK_DRIVER_MEMORY=50g spark-submit --executor-memory --total-executor-cores 200 16g --master yarn-client --conf spark.akka.threads=20 --conf spark.akka.frameSize=1024 cloud-scale-bwamem-0.1.0-assembly.jar upload-fastq -bn 1000000 1 100 /dn5/ERR09157_1.fastq /dn6/ERR09157_2.fastq ./bwamem.fastq"

Also, the output path (./bwamem.fastq) needs to be an HDFS path.

Hope the explanation helps.

**Comment by Jaeki** [comment]
Thanks for your response, one fastq file size is 256GB, so total 512 GB for the paired reads. I also have tested with 60GB of exome data. I also have tried with larger -bn option but it didn't work.
For your reference, each server has 256GB of RAM and  dual 16 processors. I believe my cluster's resource is enough. Anyway I will try again as you recommended.

**Comment by ytchen0323** [comment]
Is it possible to send me some reads in your FASTQ files? In this case, I can see if my parser handle your reads well.

**Comment by Jaeki** [comment]
Hi, Thank you for your feedback. 
I downloaded the reads data from the below link.
http://sra.dnanexus.com/runs/ERR032971

I have several but that is small one relatively.
Could you test with that data and result?
Or, Could you let me know the link of reads data that works with CS-BWAmem correctly?

Thank you.

**Comment by ytchen0323** [comment]
Hi Jaeki,
I spent some time to find out the problem. I use the SRA tool and generate the FASTQ files from the files downloaded in the above link. I found the problem is the FASTQ file format issue of ERR032971. I made some changes in the input parsing part in CS-BWAMEM. Now it can upload the ERR032971 data to HDFS and I have confirmed that the alignment part of CS-BWAMEM works as well. 

I will push the updated version to github main branch around next Monday or Tuesday. Now I am running some regression test to make sure the tool is stable.

Thanks,
Yu-Ting

**Comment by ytchen0323** [comment]
Hi Jaeki,
I have push the bug fixed version to github. Please try to git clone the 0.2.0-release branch. (P.S. the main branch is currently synchronized with 0.2.0-release but may change soon.) Please give it a try for the upload function. I appreciate your help.

Thanks,
Yu-Ting

**Comment by Jaeki** [comment]
Thank you for your work. I will try and let you know.
