### ISSUE TITLE
Trouble in compling

### ISSUE THREAD

**Issue by rydrydryd** [ytchen0323/cloud-scale-bwamem#4]
Hey guy!
I encountered some troubles in compling.
I'm wondering whether it's due to my jre version. So could you plz tell me the information about your compile environment?

**Comment by rydrydryd** [comment]
Error occurs when I execute mvn package -PotherOutputDir in src dir

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for cs.ucla.edu:jniNative:so:0.2.1
[WARNING] 'dependencies.dependency.systemPath' for cs.ucla.edu:cloud-scale-bwamem:jar should use a variable instead of a hard-coded path /home/ryd/Git/cloud-scale-bwamem/target/cloud-scale-bwamem-0.2.2-assembly.jar @ line 19, column 19
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:native-maven-plugin is missing. @ line 33, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 25, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building JNI Pair-End Smith-Waterman AVX Library 0.2.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- native-maven-plugin:1.0-alpha-8:initialize (default-initialize) @ jniNative ---
[INFO] 
[INFO] --- native-maven-plugin:1.0-alpha-8:unzipinc (default-unzipinc) @ jniNative ---
[INFO] 
[INFO] --- native-maven-plugin:1.0-alpha-8:javah (default-javah) @ jniNative ---
[INFO] 
[INFO] --- native-maven-plugin:1.0-alpha-8:javah (javah) @ jniNative ---
[INFO] /bin/sh -c cd /home/ryd/Git/cloud-scale-bwamem/target && javah -o /home/ryd/Git/cloud-scale-bwamem/target/custom-javah/jni_mate_sw.h -classpath /home/ryd/Git/cloud-scale-bwamem/target/classes:/home/ryd/Git/cloud-scale-bwamem/target/cloud-scale-bwamem-0.2.2-assembly.jar cs.ucla.edu.bwaspark.jni.HelloWorld cs.ucla.edu.bwaspark.jni.MateSWType cs.ucla.edu.bwaspark.jni.SeqSWType cs.ucla.edu.bwaspark.jni.MateSWJNI cs.ucla.edu.bwaspark.datatype.MemAlnRegType cs.ucla.edu.bwaspark.datatype.MemOptType cs.ucla.edu.bwaspark.datatype.MemPeStat cs.ucla.edu.bwaspark.datatype.FASTQSingleNode
**_error: error reading /home/ryd/Git/cloud-scale-bwamem/target/cloud-scale-bwamem-0.2.2-assembly.jar; too many entries in ZIP file
com.sun.tools.javac.util.Abort
    at com.sun.tools.javac.comp.Check.completionError(Check.java:169)
    at com.sun.tools.javadoc.DocEnv.loadClass(DocEnv.java:149)
    at com.sun.tools.javadoc.RootDocImpl.<init>(RootDocImpl.java:77)
    at com.sun.tools.javadoc.JavadocTool.getRootDocImpl(JavadocTool.java:156)
    at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:330)
    at com.sun.tools.javadoc.Start.begin(Start.java:128)
    at com.sun.tools.javadoc.Main.execute(Main.java:66)
    at com.sun.tools.javah.Main.main(Main.java:147)
javadoc: error - fatal error_**
2 errors
[INFO] 
[INFO] --- native-maven-plugin:1.0-alpha-8:compile (default-compile) @ jniNative ---
[INFO] /bin/sh -c cd /home/ryd/Git/cloud-scale-bwamem/src && gcc -s -fPIC -O2 -I/home/ryd/Git/cloud-scale-bwamem/src/main/native -I/home/ryd/Git/cloud-scale-bwamem/target/custom-javah -I/opt/oracle-jre-bin-1.7.0.80/../include -I/opt/oracle-jre-bin-1.7.0.80/../include/linux -o/home/ryd/Git/cloud-scale-bwamem/target/objs/jni_hello_world.o -c /home/ryd/Git/cloud-scale-bwamem/src/main/native/jni_hello_world.c
/home/ryd/Git/cloud-scale-bwamem/src/main/native/jni_hello_world.c:21:71: fatal error: jni_mate_sw.h: No such file or directory
 #include <jni_mate_sw.h> // generated by javah via maven-native-plugin
                                                                       ^
compilation terminated.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.995 s
[INFO] Finished at: 2016-03-29T22:52:28+08:00
[INFO] Final Memory: 7M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-8:compile (default-compile) on project jniNative: Error executing command line. Exit code:1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ytchen0323** [comment]
Hi,
To identify the error, could you provide the following information?
1. Have you successfully pass the first command "system "mvn clean package";"?
2. Do you use Java 8 or Java 7? We have tested that currently we cannot support Java 8 because use some packages come from the other group. If you use Java 7, in general there should be no problem. We have tested both Java 1.7.0_75 and 1.7.0_79.
3. The second error message seems to be some problems about files not found under the given path.
Maybe you can share your modified .pom file?

Thanks,
Yu-Ting

**Comment by rydrydryd** [comment]
Thanks guy!
I tried to change my jvm from jdk-1.8.0 to into jdk-1.7.0 and all things worked fine.
